import { Head, Link, useForm } from '@inertiajs/react';
import { ChevronLeft, GripVertical, Plus, Trash2 } from 'lucide-react';
import { FormEvent, useMemo, useState } from 'react';
import { AppShell } from '../../components/AppShell';
import type { Connector, InputField, InputType, Provider } from '../../types';

type Props = { connector: Connector | null; providers: Provider[] };
type FormData = { name: string; slug: string; description: string; provider: string; model: string; system_prompt: string; input_schema: InputField[]; output_schema: Record<string, any>; auth_mode: 'api_key' | 'none'; status: 'draft' | 'active' | 'disabled'; };
const blankField = (): InputField => ({ name: '', type: 'text', required: true, description: '' });
const blankSchema: Record<string, any> = { type: 'object', properties: {}, required: [], additionalProperties: false };

export default function ConnectorForm({ connector, providers }: Props) {
    const initial: FormData = connector ? { name: connector.name, slug: connector.slug, description: connector.description ?? '', provider: connector.provider, model: connector.model, system_prompt: connector.system_prompt, input_schema: connector.input_schema, output_schema: connector.output_schema, auth_mode: connector.auth_mode, status: connector.status } : { name: '', slug: '', description: '', provider: 'gemini', model: providers[0]?.models[0] ?? '', system_prompt: '', input_schema: [blankField()], output_schema: blankSchema, auth_mode: 'api_key', status: 'draft' };
    const form = useForm<FormData>({ ...initial });
    const [schemaText, setSchemaText] = useState(JSON.stringify(initial.output_schema, null, 2));
    const [schemaError, setSchemaError] = useState<string | null>(null);
    const selectedProvider = useMemo(() => providers.find((provider) => provider.id === form.data.provider), [form.data.provider, providers]);
    const setField = (index: number, patch: Partial<InputField>) => form.setData('input_schema', form.data.input_schema.map((field, current) => current === index ? { ...field, ...patch } : field));
    const removeField = (index: number) => form.setData('input_schema', form.data.input_schema.filter((_, current) => current !== index));
    const submit = (event: FormEvent) => { event.preventDefault(); try { const outputSchema = JSON.parse(schemaText) as Record<string, any>; setSchemaError(null); form.transform((data) => ({ ...data, output_schema: outputSchema })); connector ? form.patch(`/connectors/${connector.id}`) : form.post('/connectors'); } catch { setSchemaError('Enter valid JSON for the output schema.'); } };
    return <AppShell>
        <Head title={connector ? `Edit ${connector.name}` : 'Create connector'} />
        <section className="form-header"><Link href={connector ? `/connectors/${connector.id}` : '/connectors'} className="back-link"><ChevronLeft size={17} /> Back</Link><div><p className="eyebrow">{connector ? 'Edit connector' : 'New connector'}</p><h1>{connector ? connector.name : 'Create connector'}</h1></div></section>
        <form onSubmit={submit} className="editor-layout">
            <section className="editor-section"><div className="section-heading"><h2>Identity</h2><p>Use a stable slug for the generated API endpoint.</p></div><div className="form-grid two-columns"><label>Name<input value={form.data.name} onChange={(event) => form.setData('name', event.target.value)} placeholder="Article Writer" /></label><label>Endpoint slug<input value={form.data.slug} onChange={(event) => form.setData('slug', event.target.value)} placeholder="article-writer" /></label></div><label>Description<textarea value={form.data.description} onChange={(event) => form.setData('description', event.target.value)} placeholder="What does this API do?" rows={3} /></label>{(form.errors.name || form.errors.slug || form.errors.description) && <p className="field-error">{form.errors.name || form.errors.slug || form.errors.description}</p>}</section>
            <section className="editor-section"><div className="section-heading"><h2>AI configuration</h2><p>Provider credentials stay in server environment variables.</p></div><div className="form-grid two-columns"><label>Provider<select value={form.data.provider} onChange={(event) => { const provider = providers.find((item) => item.id === event.target.value); form.setData((data) => ({ ...data, provider: event.target.value, model: provider?.models[0] ?? '' })); }}>{providers.map((provider) => <option key={provider.id} value={provider.id}>{provider.label}</option>)}</select></label><label>Model<input list="provider-models" value={form.data.model} onChange={(event) => form.setData('model', event.target.value)} placeholder="Enter a supported model ID" /><datalist id="provider-models">{selectedProvider?.models.map((model) => <option key={model} value={model} />)}</datalist></label></div><label>System instructions<textarea value={form.data.system_prompt} onChange={(event) => form.setData('system_prompt', event.target.value)} placeholder="Explain the task, constraints, and expected response." rows={7} /></label>{(form.errors.provider || form.errors.model || form.errors.system_prompt) && <p className="field-error">{form.errors.provider || form.errors.model || form.errors.system_prompt}</p>}</section>
            <section className="editor-section"><div className="section-heading inline-heading"><div><h2>Input fields</h2><p>These fields become validation rules and the test form.</p></div><button type="button" className="secondary-button" onClick={() => form.setData('input_schema', [...form.data.input_schema, blankField()])}><Plus size={16} /> Add field</button></div><div className="field-builder">{form.data.input_schema.map((field, index) => <InputRow key={index} field={field} index={index} supportsImages={selectedProvider?.supports_images ?? false} onChange={setField} onRemove={() => removeField(index)} canRemove={form.data.input_schema.length > 1} />)}</div>{Object.entries(form.errors).filter(([key]) => key.startsWith('input_schema')).map(([key, message]) => <p className="field-error" key={key}>{message}</p>)}</section>
            <section className="editor-section"><div className="section-heading"><h2>Structured output</h2><p>Use JSON Schema to define the object returned to API callers.</p></div><label>Output schema<textarea className="code-input" value={schemaText} onChange={(event) => setSchemaText(event.target.value)} spellCheck={false} rows={13} /></label>{(schemaError || form.errors.output_schema) && <p className="field-error">{schemaError || form.errors.output_schema}</p>}</section>
            <section className="editor-section compact-section"><div className="form-grid two-columns"><label>Endpoint authentication<select value={form.data.auth_mode} onChange={(event) => form.setData('auth_mode', event.target.value as FormData['auth_mode'])}><option value="api_key">API key required</option><option value="none">No API key</option></select></label><label>Status<select value={form.data.status} onChange={(event) => form.setData('status', event.target.value as FormData['status'])}><option value="draft">Draft</option><option value="active">Active</option><option value="disabled">Disabled</option></select></label></div></section>
            <div className="form-actions"><Link href={connector ? `/connectors/${connector.id}` : '/connectors'} className="secondary-button">Cancel</Link><button className="primary-button" disabled={form.processing}>{form.processing ? 'Saving...' : connector ? 'Save changes' : 'Create connector'}</button></div>
        </form>
    </AppShell>;
}

function InputRow({ field, index, supportsImages, onChange, onRemove, canRemove }: { field: InputField; index: number; supportsImages: boolean; onChange: (index: number, patch: Partial<InputField>) => void; onRemove: () => void; canRemove: boolean }) {
    const types: InputType[] = supportsImages ? ['text', 'number', 'boolean', 'image', 'file', 'json'] : ['text', 'number', 'boolean', 'json'];
    return <div className="field-row"><span className="drag-handle" aria-hidden="true"><GripVertical size={18} /></span><label>Name<input value={field.name} onChange={(event) => onChange(index, { name: event.target.value })} placeholder="topic" /></label><label>Type<select value={field.type} onChange={(event) => onChange(index, { type: event.target.value as InputType })}>{types.map((type) => <option key={type} value={type}>{type}</option>)}</select></label><label>Description<input value={field.description ?? ''} onChange={(event) => onChange(index, { description: event.target.value })} placeholder="Explain this input" /></label><label className="checkbox-label"><input type="checkbox" checked={field.required} onChange={(event) => onChange(index, { required: event.target.checked })} /> Required</label><button type="button" className="icon-button danger-button" onClick={onRemove} disabled={!canRemove} aria-label={`Remove input field ${index + 1}`} title="Remove input field"><Trash2 size={17} /></button></div>;
}
